//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QMSRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QMSRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QMS.Core.Resources.QMSRes", typeof(QMSRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Animals.
        /// </summary>
        public static string AcceptedAnimals {
            get {
                return ResourceManager.GetString("AcceptedAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Animals.
        /// </summary>
        public static string AcceptedAnimals1 {
            get {
                return ResourceManager.GetString("AcceptedAnimals1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Animals.
        /// </summary>
        public static string AcceptedAnimals2 {
            get {
                return ResourceManager.GetString("AcceptedAnimals2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Branch.
        /// </summary>
        public static string AddNewBranch {
            get {
                return ResourceManager.GetString("AddNewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Branch.
        /// </summary>
        public static string AddNewBranch1 {
            get {
                return ResourceManager.GetString("AddNewBranch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Test.
        /// </summary>
        public static string AddTests {
            get {
                return ResourceManager.GetString("AddTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount1 {
            get {
                return ResourceManager.GetString("Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Label.
        /// </summary>
        public static string AnimalLabel {
            get {
                return ResourceManager.GetString("AnimalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals Labels.
        /// </summary>
        public static string AnimalsLabels {
            get {
                return ResourceManager.GetString("AnimalsLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Tag.
        /// </summary>
        public static string AnimalTag {
            get {
                return ResourceManager.GetString("AnimalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Tag.
        /// </summary>
        public static string AnimalTag1 {
            get {
                return ResourceManager.GetString("AnimalTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Type.
        /// </summary>
        public static string Animan_TYPE_NAME {
            get {
                return ResourceManager.GetString("Animan_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Type.
        /// </summary>
        public static string Animan_TYPE_NAME1 {
            get {
                return ResourceManager.GetString("Animan_TYPE_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Type.
        /// </summary>
        public static string Animan_TYPE_NAME2 {
            get {
                return ResourceManager.GetString("Animan_TYPE_NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Branches.
        /// </summary>
        public static string AssociatedBranches {
            get {
                return ResourceManager.GetString("AssociatedBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Branches.
        /// </summary>
        public static string AssociatedBranches1 {
            get {
                return ResourceManager.GetString("AssociatedBranches1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName1 {
            get {
                return ResourceManager.GetString("BankName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string BankName2 {
            get {
                return ResourceManager.GetString("BankName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch1 {
            get {
                return ResourceManager.GetString("Batch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Details.
        /// </summary>
        public static string BatchDetails {
            get {
                return ResourceManager.GetString("BatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Details.
        /// </summary>
        public static string BatchDetails1 {
            get {
                return ResourceManager.GetString("BatchDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Id.
        /// </summary>
        public static string BatchId {
            get {
                return ResourceManager.GetString("BatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Lables.
        /// </summary>
        public static string batchLables {
            get {
                return ResourceManager.GetString("batchLables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Lables.
        /// </summary>
        public static string batchLables1 {
            get {
                return ResourceManager.GetString("batchLables1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Lables.
        /// </summary>
        public static string batchLables2 {
            get {
                return ResourceManager.GetString("batchLables2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch is not ready for release for the following reasons:.
        /// </summary>
        public static string BatchNotReadyForRelease {
            get {
                return ResourceManager.GetString("BatchNotReadyForRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        public static string BatchNumber {
            get {
                return ResourceManager.GetString("BatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        public static string BatchNumber1 {
            get {
                return ResourceManager.GetString("BatchNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        public static string BatchNumber2 {
            get {
                return ResourceManager.GetString("BatchNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to batch of exporter .
        /// </summary>
        public static string BatchOfExporter {
            get {
                return ResourceManager.GetString("BatchOfExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch is ready for release..
        /// </summary>
        public static string BatchReadyForRelease {
            get {
                return ResourceManager.GetString("BatchReadyForRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Establishment Date.
        /// </summary>
        public static string BIRTH_ESTABLISHMENT_DATE {
            get {
                return ResourceManager.GetString("BIRTH_ESTABLISHMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Establishment Date.
        /// </summary>
        public static string BIRTH_ESTABLISHMENT_DATE1 {
            get {
                return ResourceManager.GetString("BIRTH_ESTABLISHMENT_DATE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Establishment Date.
        /// </summary>
        public static string BIRTH_ESTABLISHMENT_DATE2 {
            get {
                return ResourceManager.GetString("BIRTH_ESTABLISHMENT_DATE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string BranchName1 {
            get {
                return ResourceManager.GetString("BranchName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string BranchName2 {
            get {
                return ResourceManager.GetString("BranchName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity1 {
            get {
                return ResourceManager.GetString("Capacity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity2 {
            get {
                return ResourceManager.GetString("Capacity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Name.
        /// </summary>
        public static string ChemicalName {
            get {
                return ResourceManager.GetString("ChemicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Name.
        /// </summary>
        public static string ChemicalName1 {
            get {
                return ResourceManager.GetString("ChemicalName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string ChemicalPreQuarentineMandatory {
            get {
                return ResourceManager.GetString("ChemicalPreQuarentineMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string ChemicalPreQuarentineMandatory1 {
            get {
                return ResourceManager.GetString("ChemicalPreQuarentineMandatory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string ChemicalPreQuarentineNever {
            get {
                return ResourceManager.GetString("ChemicalPreQuarentineNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string ChemicalPreQuarentineNever1 {
            get {
                return ResourceManager.GetString("ChemicalPreQuarentineNever1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string ChemicalPreQuarentineOptional {
            get {
                return ResourceManager.GetString("ChemicalPreQuarentineOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string ChemicalPreQuarentineOptional1 {
            get {
                return ResourceManager.GetString("ChemicalPreQuarentineOptional1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Type.
        /// </summary>
        public static string ChemicalType {
            get {
                return ResourceManager.GetString("ChemicalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Type.
        /// </summary>
        public static string ChemicalType1 {
            get {
                return ResourceManager.GetString("ChemicalType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Type.
        /// </summary>
        public static string ChemicalType2 {
            get {
                return ResourceManager.GetString("ChemicalType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ChemicalTypeAmount {
            get {
                return ResourceManager.GetString("ChemicalTypeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ChemicalTypeAmount1 {
            get {
                return ResourceManager.GetString("ChemicalTypeAmount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ChemicalTypeAmount2 {
            get {
                return ResourceManager.GetString("ChemicalTypeAmount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injections.
        /// </summary>
        public static string ChemicalTypeInjections {
            get {
                return ResourceManager.GetString("ChemicalTypeInjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injections.
        /// </summary>
        public static string ChemicalTypeInjections1 {
            get {
                return ResourceManager.GetString("ChemicalTypeInjections1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pills.
        /// </summary>
        public static string ChemicalTypePills {
            get {
                return ResourceManager.GetString("ChemicalTypePills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pills.
        /// </summary>
        public static string ChemicalTypePills1 {
            get {
                return ResourceManager.GetString("ChemicalTypePills1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spray.
        /// </summary>
        public static string ChemicalTypeSpray {
            get {
                return ResourceManager.GetString("ChemicalTypeSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spray.
        /// </summary>
        public static string ChemicalTypeSpray1 {
            get {
                return ResourceManager.GetString("ChemicalTypeSpray1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Case.
        /// </summary>
        public static string ClinicCase {
            get {
                return ResourceManager.GetString("ClinicCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Type.
        /// </summary>
        public static string ClinicCaseType {
            get {
                return ResourceManager.GetString("ClinicCaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Tests.
        /// </summary>
        public static string ClinicTests {
            get {
                return ResourceManager.GetString("ClinicTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate1 {
            get {
                return ResourceManager.GetString("CreationDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status.
        /// </summary>
        public static string CurrentStatus1 {
            get {
                return ResourceManager.GetString("CurrentStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string Dash1 {
            get {
                return ResourceManager.GetString("Dash1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Entered.
        /// </summary>
        public static string DateEntered {
            get {
                return ResourceManager.GetString("DateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Entered.
        /// </summary>
        public static string DateEntered1 {
            get {
                return ResourceManager.GetString("DateEntered1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Average Weight.
        /// </summary>
        public static string DEFAULT_AVERAGE_WEIGHT {
            get {
                return ResourceManager.GetString("DEFAULT_AVERAGE_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Average Weight.
        /// </summary>
        public static string DEFAULT_AVERAGE_WEIGHT1 {
            get {
                return ResourceManager.GetString("DEFAULT_AVERAGE_WEIGHT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Average Weight.
        /// </summary>
        public static string DEFAULT_AVERAGE_WEIGHT2 {
            get {
                return ResourceManager.GetString("DEFAULT_AVERAGE_WEIGHT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destenation.
        /// </summary>
        public static string DestenationID {
            get {
                return ResourceManager.GetString("DestenationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destenation.
        /// </summary>
        public static string DestenationID1 {
            get {
                return ResourceManager.GetString("DestenationID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destenation.
        /// </summary>
        public static string DestenationID2 {
            get {
                return ResourceManager.GetString("DestenationID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destenation Name.
        /// </summary>
        public static string DestenationName {
            get {
                return ResourceManager.GetString("DestenationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destenation Name.
        /// </summary>
        public static string DestenationName1 {
            get {
                return ResourceManager.GetString("DestenationName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destenation Name.
        /// </summary>
        public static string DestenationName2 {
            get {
                return ResourceManager.GetString("DestenationName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposal Thresold (%).
        /// </summary>
        public static string DisposalThresold {
            get {
                return ResourceManager.GetString("DisposalThresold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposal Thresold (%).
        /// </summary>
        public static string DisposalThresold1 {
            get {
                return ResourceManager.GetString("DisposalThresold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose.
        /// </summary>
        public static string Dispose {
            get {
                return ResourceManager.GetString("Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed Animals.
        /// </summary>
        public static string DisposedAnimals {
            get {
                return ResourceManager.GetString("DisposedAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose Reason.
        /// </summary>
        public static string DisposeReason {
            get {
                return ResourceManager.GetString("DisposeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver License.
        /// </summary>
        public static string DriverLicense {
            get {
                return ResourceManager.GetString("DriverLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string EditSign {
            get {
                return ResourceManager.GetString("EditSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter .
        /// </summary>
        public static string ExporterName {
            get {
                return ResourceManager.GetString("ExporterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter .
        /// </summary>
        public static string ExporterName1 {
            get {
                return ResourceManager.GetString("ExporterName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter .
        /// </summary>
        public static string ExporterName2 {
            get {
                return ResourceManager.GetString("ExporterName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Weight Percentage.
        /// </summary>
        public static string FEED_WEIGHT_PERCENTAGE {
            get {
                return ResourceManager.GetString("FEED_WEIGHT_PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Weight Percentage.
        /// </summary>
        public static string FEED_WEIGHT_PERCENTAGE1 {
            get {
                return ResourceManager.GetString("FEED_WEIGHT_PERCENTAGE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Weight Percentage.
        /// </summary>
        public static string FEED_WEIGHT_PERCENTAGE2 {
            get {
                return ResourceManager.GetString("FEED_WEIGHT_PERCENTAGE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding History.
        /// </summary>
        public static string FeedingHistory {
            get {
                return ResourceManager.GetString("FeedingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding History.
        /// </summary>
        public static string FeedingHistory1 {
            get {
                return ResourceManager.GetString("FeedingHistory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding Method.
        /// </summary>
        public static string FeedingMethod {
            get {
                return ResourceManager.GetString("FeedingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding Method.
        /// </summary>
        public static string FeedingMethod1 {
            get {
                return ResourceManager.GetString("FeedingMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding Method.
        /// </summary>
        public static string FeedMethod {
            get {
                return ResourceManager.GetString("FeedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Method.
        /// </summary>
        public static string FeedMethod1 {
            get {
                return ResourceManager.GetString("FeedMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Type.
        /// </summary>
        public static string FeedType {
            get {
                return ResourceManager.GetString("FeedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Type.
        /// </summary>
        public static string FeedType1 {
            get {
                return ResourceManager.GetString("FeedType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Store.
        /// </summary>
        public static string FromStoreLabel {
            get {
                return ResourceManager.GetString("FromStoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Store.
        /// </summary>
        public static string FromStoreLabel1 {
            get {
                return ResourceManager.GetString("FromStoreLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retest If Positive Case Found.
        /// </summary>
        public static string FullTestThreshold {
            get {
                return ResourceManager.GetString("FullTestThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retest If Positive Case Found.
        /// </summary>
        public static string FullTestThreshold1 {
            get {
                return ResourceManager.GetString("FullTestThreshold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Heading to .
        /// </summary>
        public static string HeadingTo {
            get {
                return ResourceManager.GetString("HeadingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Reference.
        /// </summary>
        public static string ID_REFERENCE {
            get {
                return ResourceManager.GetString("ID_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Reference.
        /// </summary>
        public static string ID_REFERENCE1 {
            get {
                return ResourceManager.GetString("ID_REFERENCE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Reference.
        /// </summary>
        public static string ID_REFERENCE2 {
            get {
                return ResourceManager.GetString("ID_REFERENCE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string IdType1 {
            get {
                return ResourceManager.GetString("IdType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string IdType2 {
            get {
                return ResourceManager.GetString("IdType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter Type.
        /// </summary>
        public static string IndividualCorp {
            get {
                return ResourceManager.GetString("IndividualCorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter Type.
        /// </summary>
        public static string IndividualCorp1 {
            get {
                return ResourceManager.GetString("IndividualCorp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter Type.
        /// </summary>
        public static string IndividualCorp11 {
            get {
                return ResourceManager.GetString("IndividualCorp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter Type.
        /// </summary>
        public static string IndividualCorp2 {
            get {
                return ResourceManager.GetString("IndividualCorp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter Type.
        /// </summary>
        public static string IndividualCorp3 {
            get {
                return ResourceManager.GetString("IndividualCorp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Reference.
        /// </summary>
        public static string InventoryReference {
            get {
                return ResourceManager.GetString("InventoryReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Reference.
        /// </summary>
        public static string InventoryReference1 {
            get {
                return ResourceManager.GetString("InventoryReference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit Reference.
        /// </summary>
        public static string Kit {
            get {
                return ResourceManager.GetString("Kit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit Reference.
        /// </summary>
        public static string Kit1 {
            get {
                return ResourceManager.GetString("Kit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kit Reference.
        /// </summary>
        public static string Kit2 {
            get {
                return ResourceManager.GetString("Kit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Name.
        /// </summary>
        public static string MarketName {
            get {
                return ResourceManager.GetString("MarketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Name.
        /// </summary>
        public static string MarketName1 {
            get {
                return ResourceManager.GetString("MarketName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Name.
        /// </summary>
        public static string MarketName2 {
            get {
                return ResourceManager.GetString("MarketName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA1 {
            get {
                return ResourceManager.GetString("NA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative {
            get {
                return ResourceManager.GetString("Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Negative1 {
            get {
                return ResourceManager.GetString("Negative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Permitted Animals.
        /// </summary>
        public static string NoOfPermittedAnimals {
            get {
                return ResourceManager.GetString("NoOfPermittedAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Permitted Animals.
        /// </summary>
        public static string NoOfPermittedAnimals1 {
            get {
                return ResourceManager.GetString("NoOfPermittedAnimals1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Permitted Animals.
        /// </summary>
        public static string NoOfPermittedAnimals2 {
            get {
                return ResourceManager.GetString("NoOfPermittedAnimals2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number .
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number .
        /// </summary>
        public static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number .
        /// </summary>
        public static string Number2 {
            get {
                return ResourceManager.GetString("Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number / Percentage.
        /// </summary>
        public static string NumberPercentage {
            get {
                return ResourceManager.GetString("NumberPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number / Percentage.
        /// </summary>
        public static string NumberPercentage1 {
            get {
                return ResourceManager.GetString("NumberPercentage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originally Accepted.
        /// </summary>
        public static string OriginallyAccepted {
            get {
                return ResourceManager.GetString("OriginallyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Animals.
        /// </summary>
        public static string PendingAnimals {
            get {
                return ResourceManager.GetString("PendingAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Percentage of Batch.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Percentage of Batch.
        /// </summary>
        public static string Percentage1 {
            get {
                return ResourceManager.GetString("Percentage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Percentage of Batch.
        /// </summary>
        public static string Percentage2 {
            get {
                return ResourceManager.GetString("Percentage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage From Batch.
        /// </summary>
        public static string PercentageFromFullBatch {
            get {
                return ResourceManager.GetString("PercentageFromFullBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage From Batch.
        /// </summary>
        public static string PercentageFromFullBatch1 {
            get {
                return ResourceManager.GetString("PercentageFromFullBatch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage From Sample.
        /// </summary>
        public static string PercentageFromSample {
            get {
                return ResourceManager.GetString("PercentageFromSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage From Sample.
        /// </summary>
        public static string PercentageFromSample1 {
            get {
                return ResourceManager.GetString("PercentageFromSample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage From Tested.
        /// </summary>
        public static string PercentageFromTested {
            get {
                return ResourceManager.GetString("PercentageFromTested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage From Tested.
        /// </summary>
        public static string PercentageFromTested1 {
            get {
                return ResourceManager.GetString("PercentageFromTested1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Reference.
        /// </summary>
        public static string PermitReference {
            get {
                return ResourceManager.GetString("PermitReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Reference.
        /// </summary>
        public static string PermitReference1 {
            get {
                return ResourceManager.GetString("PermitReference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Reference.
        /// </summary>
        public static string PermitReference2 {
            get {
                return ResourceManager.GetString("PermitReference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNo.
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string PlusSign {
            get {
                return ResourceManager.GetString("PlusSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Positive {
            get {
                return ResourceManager.GetString("Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Positive1 {
            get {
                return ResourceManager.GetString("Positive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Cases.
        /// </summary>
        public static string PositiveCases {
            get {
                return ResourceManager.GetString("PositiveCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Cases.
        /// </summary>
        public static string PositiveCases1 {
            get {
                return ResourceManager.GetString("PositiveCases1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequarentine Process.
        /// </summary>
        public static string PreQuarentineProcess {
            get {
                return ResourceManager.GetString("PreQuarentineProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequarentine Process.
        /// </summary>
        public static string PreQuarentineProcess1 {
            get {
                return ResourceManager.GetString("PreQuarentineProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mille Quarentine Facility.
        /// </summary>
        public static string QuarantineFacility {
            get {
                return ResourceManager.GetString("QuarantineFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine period did not pass..
        /// </summary>
        public static string QuarantinePeriodNotPassed {
            get {
                return ResourceManager.GetString("QuarantinePeriodNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaratine Last Date.
        /// </summary>
        public static string QuaratineEndDate {
            get {
                return ResourceManager.GetString("QuaratineEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine Last Date.
        /// </summary>
        public static string QuaratineEndDate1 {
            get {
                return ResourceManager.GetString("QuaratineEndDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaratine Period.
        /// </summary>
        public static string QuaratinePeriod {
            get {
                return ResourceManager.GetString("QuaratinePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaratine Period.
        /// </summary>
        public static string QuaratinePeriod1 {
            get {
                return ResourceManager.GetString("QuaratinePeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine Period.
        /// </summary>
        public static string QuaratinePeriod2 {
            get {
                return ResourceManager.GetString("QuaratinePeriod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaratine Period.
        /// </summary>
        public static string QUARENTINE_PERIOD {
            get {
                return ResourceManager.GetString("QUARENTINE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaratine Period.
        /// </summary>
        public static string QUARENTINE_PERIOD1 {
            get {
                return ResourceManager.GetString("QUARENTINE_PERIOD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quaratine Period.
        /// </summary>
        public static string QUARENTINE_PERIOD2 {
            get {
                return ResourceManager.GetString("QUARENTINE_PERIOD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range1 {
            get {
                return ResourceManager.GetString("Range1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range From.
        /// </summary>
        public static string RangeFrom {
            get {
                return ResourceManager.GetString("RangeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range From.
        /// </summary>
        public static string RangeFrom1 {
            get {
                return ResourceManager.GetString("RangeFrom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range To.
        /// </summary>
        public static string RangeTo {
            get {
                return ResourceManager.GetString("RangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range To.
        /// </summary>
        public static string RangeTo1 {
            get {
                return ResourceManager.GetString("RangeTo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready For Release.
        /// </summary>
        public static string ReadyForRelease {
            get {
                return ResourceManager.GetString("ReadyForRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        public static string Reasons1 {
            get {
                return ResourceManager.GetString("Reasons1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        public static string Reasons2 {
            get {
                return ResourceManager.GetString("Reasons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept Reference.
        /// </summary>
        public static string RecieptReference {
            get {
                return ResourceManager.GetString("RecieptReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept Reference.
        /// </summary>
        public static string RecieptReference1 {
            get {
                return ResourceManager.GetString("RecieptReference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciept Reference.
        /// </summary>
        public static string RecieptReference2 {
            get {
                return ResourceManager.GetString("RecieptReference2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend Disposal.
        /// </summary>
        public static string RecommendDisposal {
            get {
                return ResourceManager.GetString("RecommendDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend disposal if this diagnosis was found.
        /// </summary>
        public static string RecommendDisposalLabel {
            get {
                return ResourceManager.GetString("RecommendDisposalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Sample Size.
        /// </summary>
        public static string RecommendedSampleSize {
            get {
                return ResourceManager.GetString("RecommendedSampleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Sample Size.
        /// </summary>
        public static string RecommendedSampleSize1 {
            get {
                return ResourceManager.GetString("RecommendedSampleSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Test Results.
        /// </summary>
        public static string RecordTests {
            get {
                return ResourceManager.GetString("RecordTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Test Results.
        /// </summary>
        public static string RecordTests1 {
            get {
                return ResourceManager.GetString("RecordTests1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string RegionName1 {
            get {
                return ResourceManager.GetString("RegionName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string RegionName2 {
            get {
                return ResourceManager.GetString("RegionName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Date.
        /// </summary>
        public static string RegisterationDate {
            get {
                return ResourceManager.GetString("RegisterationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Date.
        /// </summary>
        public static string RegisterationDate1 {
            get {
                return ResourceManager.GetString("RegisterationDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Date.
        /// </summary>
        public static string RegisterationDate2 {
            get {
                return ResourceManager.GetString("RegisterationDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Form.
        /// </summary>
        public static string RegisterationForm {
            get {
                return ResourceManager.GetString("RegisterationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Form.
        /// </summary>
        public static string RegisterationForm1 {
            get {
                return ResourceManager.GetString("RegisterationForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Form.
        /// </summary>
        public static string RegisterationForm2 {
            get {
                return ResourceManager.GetString("RegisterationForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Animals.
        /// </summary>
        public static string rejectedAnimals {
            get {
                return ResourceManager.GetString("rejectedAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Animals.
        /// </summary>
        public static string rejectedAnimals1 {
            get {
                return ResourceManager.GetString("rejectedAnimals1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Animals.
        /// </summary>
        public static string rejectedAnimals2 {
            get {
                return ResourceManager.GetString("rejectedAnimals2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarantine Clearance Certificate.
        /// </summary>
        public static string ReleaseReportTitle {
            get {
                return ResourceManager.GetString("ReleaseReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test (.
        /// </summary>
        public static string ReleaseTestValidation1 {
            get {
                return ResourceManager.GetString("ReleaseTestValidation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) is not complete..
        /// </summary>
        public static string ReleaseTestValidation2 {
            get {
                return ResourceManager.GetString("ReleaseTestValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch was not found..
        /// </summary>
        public static string RelMsgBatchNotFound {
            get {
                return ResourceManager.GetString("RelMsgBatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string Remaining1 {
            get {
                return ResourceManager.GetString("Remaining1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Tests.
        /// </summary>
        public static string RequiredTests {
            get {
                return ResourceManager.GetString("RequiredTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Tests.
        /// </summary>
        public static string RequiredTests1 {
            get {
                return ResourceManager.GetString("RequiredTests1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Tests.
        /// </summary>
        public static string RequiredTests2 {
            get {
                return ResourceManager.GetString("RequiredTests2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round 2 .
        /// </summary>
        public static string RoundRequired {
            get {
                return ResourceManager.GetString("RoundRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round 2 .
        /// </summary>
        public static string RoundRequired1 {
            get {
                return ResourceManager.GetString("RoundRequired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round 2 .
        /// </summary>
        public static string RoundRequired2 {
            get {
                return ResourceManager.GetString("RoundRequired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Size.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Size.
        /// </summary>
        public static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Size.
        /// </summary>
        public static string Sample2 {
            get {
                return ResourceManager.GetString("Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Method.
        /// </summary>
        public static string SamplingMethod {
            get {
                return ResourceManager.GetString("SamplingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Method.
        /// </summary>
        public static string SamplingMethod1 {
            get {
                return ResourceManager.GetString("SamplingMethod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Of Permit.
        /// </summary>
        public static string ScanOfPermit {
            get {
                return ResourceManager.GetString("ScanOfPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Of Permit.
        /// </summary>
        public static string ScanOfPermit1 {
            get {
                return ResourceManager.GetString("ScanOfPermit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Of Permit.
        /// </summary>
        public static string ScanOfPermit2 {
            get {
                return ResourceManager.GetString("ScanOfPermit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spray.
        /// </summary>
        public static string Spray {
            get {
                return ResourceManager.GetString("Spray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spray.
        /// </summary>
        public static string Spray1 {
            get {
                return ResourceManager.GetString("Spray1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spray.
        /// </summary>
        public static string Spray2 {
            get {
                return ResourceManager.GetString("Spray2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status1 {
            get {
                return ResourceManager.GetString("Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status2 {
            get {
                return ResourceManager.GetString("Status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Action.
        /// </summary>
        public static string TestAction {
            get {
                return ResourceManager.GetString("TestAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Action.
        /// </summary>
        public static string TestAction1 {
            get {
                return ResourceManager.GetString("TestAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Action.
        /// </summary>
        public static string TestAction2 {
            get {
                return ResourceManager.GetString("TestAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Details.
        /// </summary>
        public static string TestDetails {
            get {
                return ResourceManager.GetString("TestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Details.
        /// </summary>
        public static string TestDetails1 {
            get {
                return ResourceManager.GetString("TestDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested Animal.
        /// </summary>
        public static string TestedAnimal {
            get {
                return ResourceManager.GetString("TestedAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested Animals.
        /// </summary>
        public static string TestedAnimals {
            get {
                return ResourceManager.GetString("TestedAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested Animals.
        /// </summary>
        public static string TestedAnimals1 {
            get {
                return ResourceManager.GetString("TestedAnimals1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test All Batch if a positive case is detected.
        /// </summary>
        public static string TestFullBatchIf {
            get {
                return ResourceManager.GetString("TestFullBatchIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test All Batch if a positive case is detected.
        /// </summary>
        public static string TestFullBatchIf1 {
            get {
                return ResourceManager.GetString("TestFullBatchIf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        public static string TestName1 {
            get {
                return ResourceManager.GetString("TestName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Name.
        /// </summary>
        public static string TestName2 {
            get {
                return ResourceManager.GetString("TestName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result.
        /// </summary>
        public static string TestResult1 {
            get {
                return ResourceManager.GetString("TestResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        public static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Results.
        /// </summary>
        public static string TestResults1 {
            get {
                return ResourceManager.GetString("TestResults1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Summary.
        /// </summary>
        public static string TestSummary {
            get {
                return ResourceManager.GetString("TestSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Summary.
        /// </summary>
        public static string TestSummary1 {
            get {
                return ResourceManager.GetString("TestSummary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TYPE_NAME {
            get {
                return ResourceManager.GetString("TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TYPE_NAME1 {
            get {
                return ResourceManager.GetString("TYPE_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TYPE_NAME2 {
            get {
                return ResourceManager.GetString("TYPE_NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type1 {
            get {
                return ResourceManager.GetString("Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string VehicleMake {
            get {
                return ResourceManager.GetString("VehicleMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string VehicleYear {
            get {
                return ResourceManager.GetString("VehicleYear", resourceCulture);
            }
        }
    }
}
