//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRolePermission
    {
        public int RolePermissionId { get; set; }
        public string RoleId { get; set; }
        public string Controller { get; set; }
        public string Vieww { get; set; }
        public string CanAccess { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
