//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batchs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batchs()
        {
            this.BatchChemicals = new HashSet<BatchChemicals>();
            this.BatchLabel = new HashSet<BatchLabel>();
            this.Rejected_Animals = new HashSet<Rejected_Animals>();
            this.TESTED_ANIMALS = new HashSet<TESTED_ANIMALS>();
            this.TESTED_RANGES = new HashSet<TESTED_RANGES>();
            this.CLINIC_CASES = new HashSet<CLINIC_CASES>();
            this.DiposedBatchs = new HashSet<DiposedBatchs>();
            this.DisposeDetails = new HashSet<DisposeDetails>();
            this.PensLables = new HashSet<PensLables>();
            this.ReleaseRecord = new HashSet<ReleaseRecord>();
        }
    
        public long SYSTEMID { get; set; }
        public string NOTES { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<System.DateTime> AUTHORIZATION_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public long ExporterID { get; set; }
        public long DestenationID { get; set; }
        public long typeID { get; set; }
        public Nullable<long> AcceptedAnimals { get; set; }
        public Nullable<long> marketID { get; set; }
        public Nullable<long> PenId { get; set; }
        public string spray { get; set; }
        public string ChemicalType { get; set; }
        public Nullable<decimal> ChemicalAMT { get; set; }
        public string FeedMethod { get; set; }
        public Nullable<decimal> AverageWeight { get; set; }
        public Nullable<System.DateTime> RegisterationDate { get; set; }
        public string PermitReference { get; set; }
        public byte[] ScanOfPermit { get; set; }
        public string RecieptReference { get; set; }
        public int NoOfPermittedAnimals { get; set; }
        public string VerfiyStatus { get; set; }
        public Nullable<int> NoOFDisposed { get; set; }
    
        public virtual ANIMAL_TYPE ANIMAL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchChemicals> BatchChemicals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchLabel> BatchLabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rejected_Animals> Rejected_Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTED_ANIMALS> TESTED_ANIMALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTED_RANGES> TESTED_RANGES { get; set; }
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual EXPORTER EXPORTER { get; set; }
        public virtual PEN PEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLINIC_CASES> CLINIC_CASES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiposedBatchs> DiposedBatchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisposeDetails> DisposeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PensLables> PensLables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseRecord> ReleaseRecord { get; set; }
    }
}
