//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchLabel
    {
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> AUTHORIZATION_DATE { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string CREATED_BY { get; set; }
        public string STATUS { get; set; }
        public long BatchId { get; set; }
        public long SYSTEMID { get; set; }
        public string batchLabel1 { get; set; }
    
        public virtual Batchs Batchs { get; set; }
    }
}
