//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINIC_CASES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLINIC_CASES()
        {
            this.CASE_DIAGNOSIS1 = new HashSet<CASE_DIAGNOSIS>();
            this.CASE_SYMPTOMS = new HashSet<CASE_SYMPTOMS>();
            this.CASE_TESTS = new HashSet<CASE_TESTS>();
        }
    
        public long SYSTEMID { get; set; }
        public long BATCH_ID { get; set; }
        public string CASE_TYPE { get; set; }
        public string ANIMAL_LABEL { get; set; }
        public Nullable<long> Diagnosis { get; set; }
        public string DISPOSED { get; set; }
        public string Notes { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<System.DateTime> AUTHORIZATION_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    
        public virtual Batchs Batchs { get; set; }
        public virtual CASE_DIAGNOSIS CASE_DIAGNOSIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_DIAGNOSIS> CASE_DIAGNOSIS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_SYMPTOMS> CASE_SYMPTOMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_TESTS> CASE_TESTS { get; set; }
    }
}
