//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLRECORD
    {
        public long SYSTEMID { get; set; }
        public int PEN_OCCUPIED { get; set; }
        public int PEN_CAPACITY { get; set; }
        public int BATCH_FULL_DATA { get; set; }
        public int ANIMAL_TAG_MAX { get; set; }
        public int QUARENTINE_PERIOD_WEEKEND { get; set; }
        public int BATCH_APPROVAL { get; set; }
        public int MASTER_APPROVAL { get; set; }
    }
}
