//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPORTER()
        {
            this.Batchs = new HashSet<Batchs>();
            this.ReleaseRecord = new HashSet<ReleaseRecord>();
        }
    
        public long SYSTEMID { get; set; }
        public string EXPORTER_NAME { get; set; }
        public long EXPORTER_TYPE_ID { get; set; }
        public Nullable<long> BANK_BRANCH_ID { get; set; }
        public Nullable<long> ID_TYPE_ID { get; set; }
        public string ID_REFERENCE { get; set; }
        public Nullable<System.DateTime> BIRTH_ESTABLISHMENT_DATE { get; set; }
        public string NOTES { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<long> AUTHORIZED_BY { get; set; }
        public long LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime AUTHORIZATION_DATE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batchs> Batchs { get; set; }
        public virtual BRANCH BRANCH { get; set; }
        public virtual ID_TYPE ID_TYPE { get; set; }
        public virtual EXPORTER_TYPE EXPORTER_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseRecord> ReleaseRecord { get; set; }
    }
}
