//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QMSEntities : DbContext
    {
        public QMSEntities()
            : base("name=QMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<ANIMAL_TYPE> ANIMAL_TYPE { get; set; }
        public virtual DbSet<BANK> BANK { get; set; }
        public virtual DbSet<BatchChemicals> BatchChemicals { get; set; }
        public virtual DbSet<BatchLabel> BatchLabel { get; set; }
        public virtual DbSet<Batchs> Batchs { get; set; }
        public virtual DbSet<BRANCH> BRANCH { get; set; }
        public virtual DbSet<CASE_DIAGNOSIS> CASE_DIAGNOSIS { get; set; }
        public virtual DbSet<CASE_SYMPTOMS> CASE_SYMPTOMS { get; set; }
        public virtual DbSet<CASE_TESTS> CASE_TESTS { get; set; }
        public virtual DbSet<CHEMICAL> CHEMICAL { get; set; }
        public virtual DbSet<CHEMICAL_DOSE> CHEMICAL_DOSE { get; set; }
        public virtual DbSet<CLINIC_CASES> CLINIC_CASES { get; set; }
        public virtual DbSet<CONTACT> CONTACT { get; set; }
        public virtual DbSet<CONTROLRECORD> CONTROLRECORD { get; set; }
        public virtual DbSet<DESTINATION> DESTINATION { get; set; }
        public virtual DbSet<DESTINATION_TESTS> DESTINATION_TESTS { get; set; }
        public virtual DbSet<DIAGNOSES> DIAGNOSES { get; set; }
        public virtual DbSet<DiposedBatchs> DiposedBatchs { get; set; }
        public virtual DbSet<DisposeDetails> DisposeDetails { get; set; }
        public virtual DbSet<DisposeMethod> DisposeMethod { get; set; }
        public virtual DbSet<DRIVERS> DRIVERS { get; set; }
        public virtual DbSet<EXPORTER> EXPORTER { get; set; }
        public virtual DbSet<EXPORTER_TYPE> EXPORTER_TYPE { get; set; }
        public virtual DbSet<FEED_RECORD> FEED_RECORD { get; set; }
        public virtual DbSet<FEED_TYPE> FEED_TYPE { get; set; }
        public virtual DbSet<ID_TYPE> ID_TYPE { get; set; }
        public virtual DbSet<MARKET> MARKET { get; set; }
        public virtual DbSet<PEN> PEN { get; set; }
        public virtual DbSet<PensLables> PensLables { get; set; }
        public virtual DbSet<QUARENTINE_PERIOD> QUARENTINE_PERIOD { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<Rejected_Animals> Rejected_Animals { get; set; }
        public virtual DbSet<ReleaseDetails> ReleaseDetails { get; set; }
        public virtual DbSet<ReleaseRecord> ReleaseRecord { get; set; }
        public virtual DbSet<SYMPTOMS> SYMPTOMS { get; set; }
        public virtual DbSet<TESTED_ANIMALS> TESTED_ANIMALS { get; set; }
        public virtual DbSet<TESTED_RANGES> TESTED_RANGES { get; set; }
        public virtual DbSet<TestKits> TestKits { get; set; }
        public virtual DbSet<TESTS> TESTS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<TEST_SUMMARY> TEST_SUMMARY { get; set; }
        public virtual DbSet<VEHICLES> VEHICLES { get; set; }
        public virtual DbSet<VEHICLES_MAKE> VEHICLES_MAKE { get; set; }
        public virtual DbSet<VEHICLES_MODEL> VEHICLES_MODEL { get; set; }
    }
}
