//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensLables
    {
        public long SYSTEMID { get; set; }
        public string NOTES { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<long> AUTHORIZED_BY { get; set; }
        public long LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public long PenId { get; set; }
        public long batchId { get; set; }
        public string lableRanges { get; set; }
        public string color { get; set; }
        public Nullable<int> Range { get; set; }
    
        public virtual Batchs Batchs { get; set; }
        public virtual PEN PEN { get; set; }
    }
}
