//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUARENTINE_PERIOD
    {
        public long SYSTEMID { get; set; }
        public long DESTINATION_ID { get; set; }
        public long ANIMAL_TYPE_ID { get; set; }
        public int QUARENTINE_DAYS { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime AUTHORIZATION_DATE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    
        public virtual ANIMAL_TYPE ANIMAL_TYPE { get; set; }
        public virtual DESTINATION DESTINATION { get; set; }
    }
}
