//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseDetails
    {
        public long SYSTEMID { get; set; }
        public long ReleaseRecordId { get; set; }
        public string AnimalTag1 { get; set; }
        public string AnimalTag2 { get; set; }
        public string AnimalTag3 { get; set; }
        public string AnimalTag4 { get; set; }
    
        public virtual ReleaseRecord ReleaseRecord { get; set; }
    }
}
