//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReleaseRecord()
        {
            this.ReleaseDetails = new HashSet<ReleaseDetails>();
        }
    
        public long SYSTEMID { get; set; }
        public long BatchId { get; set; }
        public long ExporterId { get; set; }
        public long DestinationId { get; set; }
        public long AnimalTypeId { get; set; }
        public string QuarantineFacility { get; set; }
        public string ReportTitle { get; set; }
        public int AnimalCount { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<System.DateTime> AUTHORIZATION_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    
        public virtual ANIMAL_TYPE ANIMAL_TYPE { get; set; }
        public virtual Batchs Batchs { get; set; }
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual EXPORTER EXPORTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseDetails> ReleaseDetails { get; set; }
    }
}
