//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TESTS()
        {
            this.CASE_TESTS = new HashSet<CASE_TESTS>();
            this.DESTINATION_TESTS = new HashSet<DESTINATION_TESTS>();
            this.TESTED_ANIMALS = new HashSet<TESTED_ANIMALS>();
            this.TESTED_RANGES = new HashSet<TESTED_RANGES>();
            this.TestKits = new HashSet<TestKits>();
        }
    
        public long SYSTEMID { get; set; }
        public string TEST_NAME { get; set; }
        public string NOTES { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<System.DateTime> AUTHORIZATION_DATE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string Sample { get; set; }
        public string TestAction { get; set; }
        public string RoundRequired { get; set; }
        public string Kits { get; set; }
        public string Percentage { get; set; }
        public string Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_TESTS> CASE_TESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESTINATION_TESTS> DESTINATION_TESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTED_ANIMALS> TESTED_ANIMALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TESTED_RANGES> TESTED_RANGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestKits> TestKits { get; set; }
    }
}
