//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_SUMMARY
    {
        public long BATCH_ID { get; set; }
        public long TEST_ID { get; set; }
        public string TEST_NAME { get; set; }
        public Nullable<long> ACCEPTED_ANIMALS { get; set; }
        public string SAMPLING_METHOD { get; set; }
        public Nullable<long> RECOMMENDED_SAMPLE_SIZE { get; set; }
        public Nullable<int> TESTED_ANIMALS { get; set; }
        public Nullable<int> POSITIVE_CASES { get; set; }
        public string CURRENT_STATUS { get; set; }
    }
}
